kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
    name: repl-autoscaler
    namespace: repl
spec:
    minReplicas: 2
    maxReplicas: 8
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: repl-deploy
    targetCPUUtilizationPercentage: 80
