apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: repl-autoscaler
spec:
    minReplicas: 2
    maxReplicas: 5
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: repl-app
    targetCPUUtilizationPercentage: 80
