apiVersion: v1
kind: Service
metadata:
  name: repl1-svc
  labels:
    app: repl-app
spec:
  ports:
    - port: 443
      targetPort: 8080
      name: https
  selector:
    app: repl-app
  type: LoadBalancer
